### PR TITLE
add support for SUSE

### PR DESCRIPTION
**Pull request by psladek**
- init.sls also provides chroot dir
 - and checks if anonymous dir exists if used

### CODE REVIEW

**Comment by aboe76** [comment]
@psladek aren't you forgetting an updated map.jinja file?

**Comment by RabidCicada** [comment]
It's been a while since I have played with salt.  I'll have to spin up on it again AND I'm in the middle of a lot of real life stuff right now.  No promises on when I'll get to this....though I will try.  If someone else can give a sniff test, and approve...I'm ok with that.

**Comment by psladek** [comment]
@aboe76 yes, sorry, somehow missed that. 
Fixed, updated map.jinja now included.

**Comment by aboe76** [comment]
@psladek no problem merged.

**Comment by RabidCicada** [comment]
Ty!

**Pull request merged**
